// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_getVideo from "./routes/api/getVideo.ts";
import * as $index from "./routes/index.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Media from "./islands/Media.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/getVideo.ts": $api_getVideo,
    "./routes/index.tsx": $index,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Media.tsx": $Media,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
