// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_stream from "./routes/api/stream.ts";
import * as $index from "./routes/index.tsx";
import * as $videos_video_ from "./routes/videos/[video].tsx";
import * as $videos_feed from "./routes/videos/feed.tsx";
import * as $Feed from "./islands/Feed.tsx";
import * as $Media from "./islands/Media.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/stream.ts": $api_stream,
    "./routes/index.tsx": $index,
    "./routes/videos/[video].tsx": $videos_video_,
    "./routes/videos/feed.tsx": $videos_feed,
  },
  islands: {
    "./islands/Feed.tsx": $Feed,
    "./islands/Media.tsx": $Media,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
